{
 "title": "Flux Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "DS_LOKI", "query": "loki" },
   { "name": "logs_search" }
  ]
 },
 "panels": [
  {
   "title": "Number of Manifests Synced",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flux_daemon_sync_manifests{success=\"true\"} > 0",
     "legendFormat": "Synced Manifests"
    },
    {
     "expr": "flux_daemon_sync_manifests{success=\"false\"} > 0",
     "legendFormat": "Synced Manifest Failures"
    }
   ]
  },
  {
   "title": "Sync Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(flux_daemon_sync_duration_seconds_count{success=\"true\"}[5m]) > 0",
     "legendFormat": "Sync Duration"
    },
    {
     "expr": "delta(flux_daemon_sync_duration_seconds_count{success=\"false\"}[5m]) > 0",
     "legendFormat": "Sync Duration Failure"
    }
   ]
  },
  {
   "title": "Duration of Git-to-Cluster Sync",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "delta(flux_daemon_sync_duration_seconds_sum{success=\"true\"}[5m])",
     "legendFormat": "Sync Duration"
    }
   ]
  },
  {
   "title": "Flux Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{app=\"flux\"} |~ \"$logs_search\""
    }
   ]
  }
 ]
}