#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [ ! $(command -v gometalinter) ]
then
	go get github.com/alecthomas/gometalinter
	gometalinter --update --install
fi

gometalinter \
	--vendor \
	--exclude='error return value not checked.*(Close|Log|Print|Encode).*\(errcheck\)$' \
	--exclude='.*_test\.go:.*error return value not checked.*\(errcheck\)$' \
	--exclude='duplicate of.*_test.go.*\(dupl\)$' \
	--disable=aligncheck \
	--disable=gotype \
	--disable=dupl \
	--cyclo-over=20 \
	--tests \
	--deadline=60s \
	$*
