{{- if and .Values.rbac.create (eq .Values.clusterRole.create false) -}}
{{- $rules := .Values.rbac.rules -}}
{{- range $namespace := (append .Values.allowedNamespaces .Release.Namespace) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "flux.fullname" $ }}
  namespace: {{ $namespace }}
  labels:
    app: {{ template "flux.name" $ }}
    chart: {{ template "flux.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
rules: {{ $rules | toYaml | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "flux.fullname" $ }}
  namespace: {{ $namespace }}
  labels:
    app: {{ template "flux.name" $ }}
    chart: {{ template "flux.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "flux.fullname" $ }}
subjects:
  - name: {{ template "flux.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace | quote }}
    kind: ServiceAccount
---
{{- end }}
{{- end -}}
