/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	integrations_flux_v1 "github.com/weaveworks/flux/apis/integrations.flux/v1"
	versioned "github.com/weaveworks/flux/integrations/client/clientset/versioned"
	internalinterfaces "github.com/weaveworks/flux/integrations/client/informers/externalversions/internalinterfaces"
	v1 "github.com/weaveworks/flux/integrations/client/listers/integrations/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// FluxHelmResourceInformer provides access to a shared informer and lister for
// FluxHelmResources.
type FluxHelmResourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.FluxHelmResourceLister
}

type fluxHelmResourceInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewFluxHelmResourceInformer constructs a new informer for FluxHelmResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFluxHelmResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				return client.IntegrationsV1().FluxHelmResources(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				return client.IntegrationsV1().FluxHelmResources(namespace).Watch(options)
			},
		},
		&integrations_flux_v1.FluxHelmResource{},
		resyncPeriod,
		indexers,
	)
}

func defaultFluxHelmResourceInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFluxHelmResourceInformer(client, meta_v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *fluxHelmResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&integrations_flux_v1.FluxHelmResource{}, defaultFluxHelmResourceInformer)
}

func (f *fluxHelmResourceInformer) Lister() v1.FluxHelmResourceLister {
	return v1.NewFluxHelmResourceLister(f.Informer().GetIndexer())
}
