FROM alpine:3.6

RUN apk add --no-cache ca-certificates tini

COPY ./ecr-sidecar /usr/local/bin

ENTRYPOINT [ "/sbin/tini", "--", "ecr-sidecar" ]

ARG BUILD_DATE
ARG VCS_REF

# These will change for every build
LABEL org.opencontainers.image.revision="$VCS_REF" \
      org.opencontainers.image.created="$BUILD_DATE" \
      org.label-schema.vcs-ref="$VCS_REF" \
      org.label-schema.build-date="$BUILD_DATE"
