name: Build snap

on: push

jobs:
  build-snap:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      - name: Run Snapcraft build
        run: snapcraft
